### ISSUE TITLE
Website does not allow me to register

### ISSUE THREAD

**Issue by tp9** [PygameProjects/OpenSource_rpg#12]
I tried registering a new account at python-dev.tk but received an error screen. When I tried to log in with my account and password I received an 'incorrect username and password' error.

**Comment by MihaiPro** [comment]
post error screen, do you activated your email after sign up?

**Comment by tp9** [comment]
Thanks for the reply. I just tried it from home and it worked. Maybe the firewall at work was causing a problem. Closing this issue.
